# Generated by Django 5.1 on 2024-08-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tax_id', models.IntegerField()),
                ('abundance_score', models.FloatField()),
                ('relative_abundance', models.FloatField()),
                ('unique_matches_frequency', models.IntegerField()),
            ],
        ),
    ]
